
# Makefile for PT8641 PROJECT


# WL(1) means Lists only those warnings which may generate
#       incorrect code (Cx51 Compiler User's Guide, page 85)
#
# Linker controls: DISABLEWARNING
#                  A51/AX51/A251 Macro Assembler and Utilities
#                  page 307.

AFLAGS = NOPRINT
CFLAGS = DB OE NOPR WL(1) OPTIMIZE(9,SPEED) LARGE

AA51= c:\Cygnal\IDEfiles\c51\Bin\a51
CC51= c:\Cygnal\IDEfiles\c51\Bin\c51
LN51= c:\Cygnal\IDEfiles\c51\Bin\bl51

.c.obj:
      $(CC51) $&.c $(CFLAGS)

.a51.obj:
      $(AA51) $&.a51 $(AFLAGS)


a.abs: PT8641.obj cmd.obj eeprom.obj ini.obj ser_spi.obj micro.obj lenval.obj ports.obj serial.obj

   del a.m51
   $(LN51) @LINKRSP
   c:\Cygnal\IDEfiles\c51\Bin\OH51 a.abs
   HB80 a.hex a.bin

PT8641.obj:   PT8641.c
ser_spi.obj:  ser_spi.c
cmd.obj:      cmd.c
eeprom.obj:   eeprom.c
ini.obj:      ini.c
micro.obj:    micro.c
ports.obj:    ports.c
lenval.obj:   lenval.c
serial.obj:   serial.c


