/* cres.h - RTXC Resource include file */

#define NRES 25
#define DNRES 256

#define SIORES   1 /* Serial resource      */
#define MODE_RES 2 /* Mode_Object          */
#define FEND_RES 3 /* FrontEnd_Object      */
#define ALAM_RES 4 /* Alarm_Object         */
#define BER_RES  5 /* Ber_Object           */
#define LEVL_RES 6 /* Level_Object         */
#define ELOG_RES 7 /* EventLog_Object      */
#define NOIS_RES 8 /* Noise_Object         */
#define FRON_RES 9 /* Front_Object         */
#define REMO_RES 10 /* Remote_Object        */
#define REM_IRES 11 /* RemoteIn_DeviceDrv   */
#define REM_ORES 12 /* RemoteOut_DeviceDrv  */
#define KEY_RES  13 /* Keyboard_DeviceDrv   */
#define LED_RES  14 /* Led_DeviceDrv        */
#define HW_RES   15 /* Hardware_DeviceDrv   */
#define PAR_RES  16 /* Parallel_DeviceDrv   */
#define DIS_RES  17 /* Display_DeviceDrv    */
#define REAL_RES 18 /* RealTimeClk_DeviceDr */
#define NV_RES   19 /* NVRam_DeviceDrv      */
#define FEC1_RES 20 /* Fec1_DeviceDrv       */
#define FEC2_RES 21 /* Fec2_DeviceDrv       */
#define COF_RES  22 /* LsiCofdm_DeviceDrv   */
#define ALRM_RES 23 /* Alarm_DeviceDrv      */
#define TUNI_RES 24 /* TunerInput_DeviceDrv */
#define TUNF_RES 25 /* TunerFreq_DeviceDrv  */

/* End of file - cres.h */
