--------------------------------------------------------------------------------
-- Copyright (c) 1995-2003 Xilinx, Inc.
-- All Right Reserved.
--------------------------------------------------------------------------------
--   ____  ____ 
--  /   /\/   / 
-- /___/  \  /    Vendor: Xilinx 
-- \   \   \/     Version : 1.0
--  \   \         Application : 
--  /   /         Filename : X:\xw\8612\Xilinx_test\RktIO_test\RktIO.vhd
-- /___/   /\     Timestamp : 8-09-2005 09:31:43
-- \   \  /  \ 
--  \___\/\___\ 
--
--Command: 
--Design Name: X:\xw\8612\Xilinx_test\RktIO_test\RktIO.vhd
-- Module Name: MY_GT11

-- Generated by Xilinx V4 Wizard

library ieee;
use ieee.std_logic_1164.ALL;
use ieee.numeric_std.ALL;
library UNISIM;
use UNISIM.Vcomponents.ALL;

entity MY_GT11 is
   port ( 
          RX1N_IN                      : in    std_logic; 
          RX1P_IN                      : in    std_logic; 
          TX1N_OUT                     : out   std_logic; 
          TX1P_OUT                     : out   std_logic;
          RXRECCLK1_OUT                : out   std_logic; 
          TXOUTCLK1_OUT                : out   std_logic; 
          TXOUTCLK2_OUT                : out   std_logic; 
          RXUSRCLK2_IN                 : in    std_logic; 
          TXUSRCLK_IN                  : in    std_logic; 
          TXUSRCLK2_IN                 : in    std_logic; 
 		    GREFCLK_IN                   : in    std_logic; 
      --    REFCLK1_IN                   : in    std_logic; 
          RXDATA_OUT                   : out   std_logic_vector (7 downto 0);  
          TXDATA_IN                    : in    std_logic_vector (9 downto 0)	
          );
end MY_GT11;

architecture BEHAVIORAL of MY_GT11 is

    signal TXKERR_OUT_FLOAT         : std_logic_vector (7 downto 0); 
    signal TXRUNDISP_OUT_FLOAT      : std_logic_vector (7 downto 0); 
    signal RXCHARISK_OUT_FLOAT      : std_logic_vector (7 downto 0); 
    signal RXRUNDISP_OUT_FLOAT      : std_logic_vector (7 downto 0); 
    signal RXDISPERR_OUT_FLOAT      : std_logic_vector (7 downto 0); 
    signal RXCHARISCOMMA_OUT_FLOAT  : std_logic_vector (7 downto 0); 
    signal RXNOTINTABLE_OUT_FLOAT   : std_logic_vector (7 downto 0); 
    signal RXDATA_OUT_FLOAT         : std_logic_vector (64 downto 0); 
   
begin
   GT11_CUSTOM_INST : GT11
   --INST_GT11 : GT11
	generic map( 
   
--------------RocketIO MGT CRC Attributes-------------
	RXCRCCLOCKDOUBLE => FALSE,
	RXCRCINITVAL => x"FFFFFFFF",
	RXCRCSAMECLOCK => FALSE,
	TXCRCCLOCKDOUBLE => FALSE,
	TXCRCINITVAL => x"FFFFFFFF",
	TXCRCSAMECLOCK => FALSE,
	RXCRCENABLE => FALSE,
	RXCRCINVERTGEN => FALSE,
	TXCRCENABLE => FALSE,
	TXCRCINVERTGEN => FALSE,
	
---------------RocketIO MGT PMA Attributes-------------	
	FDET_LCK_SEL => "001",
	FDET_HYS_SEL => "100",
	FDET_LCK_CAL => "100",
	FDET_HYS_CAL => "010",
	VCODAC_INIT => "0000000000",
	TXFDCAL_CLOCK_DIVIDE =>  "NONE",
	LOOPCAL_WAIT => "00",
	RXFDET_LCK_SEL => "111",
	RXFDET_HYS_SEL => "001",
	RXFDET_LCK_CAL => "101",
	RXFDET_HYS_CAL => "010",
	RXVCODAC_INIT => "0001000001",
	RXFDCAL_CLOCK_DIVIDE => "TWO",
	RXLOOPCAL_WAIT => "00",
	
---------------Drivers/Buffers--------------------------	
	RXAFEEQ => "000000000",
	RXDCCOUPLE => FALSE,
	RXEQ => x"4000000000000000",
	TXDAT_TAP_DAC => "10000",
	TXPOST_TAP_DAC => "00111",
	TXHIGHSIGNALEN => TRUE,
	TXPOST_TAP_PD => TRUE,
	TXPRE_TAP_DAC => "00000",
	TXPRE_TAP_PD => TRUE,
	TXSLEWRATE => FALSE,
	TXTERMTRIM => "1100",
	
---------------Clocks----------------------------------	
	RXCLKMODE => "100111",
	RXOUTDIV2SEL => 2,
	RXPLLNDIVSEL => 8,
	RXPMACLKSEL => "GREFCLK", --REFCLK1
	RXRECCLK1_USE_SYNC => FALSE,
	TXABPMACLKSEL => "GREFCLK",
	TXCLKMODE => "0100",
	TXOUTCLK1_USE_SYNC => FALSE,
	TXOUTDIV2SEL => 4,
	TXPHASESEL => FALSE,
	TXPLLNDIVSEL => 20,
	
----------------Miscellaneous-------------------------	
	RXCDRLOS => "000000",
	RXLKADJ => "00000",
	RXPD => FALSE,
	RXRSDPD => FALSE,
	TXPD => FALSE,
	PMACOREPWRENABLE => TRUE,
	PMA_BIT_SLIP => FALSE,
	
--------------MGT PCS Attributes----------------------	
--Channel Bonding
	CCCB_ARBITRATOR_DISABLE => FALSE,
	CHAN_BOND_LIMIT => 16,
	CHAN_BOND_MODE => "NONE",
	CHAN_BOND_ONE_SHOT => FALSE,
	CHAN_BOND_SEQ_1_1 => "00000000000",
	CHAN_BOND_SEQ_1_2 => "00000000000",
	CHAN_BOND_SEQ_1_3 => "00000000000",
	CHAN_BOND_SEQ_1_4 => "00000000000",
	CHAN_BOND_SEQ_1_MASK => "1110",
	CHAN_BOND_SEQ_2_1 => "00000000000",
	CHAN_BOND_SEQ_2_2 => "00000000000",
	CHAN_BOND_SEQ_2_3 => "00000000000",
	CHAN_BOND_SEQ_2_4 => "00000000000",
	CHAN_BOND_SEQ_2_MASK => "1110",
	CHAN_BOND_SEQ_2_USE => FALSE,
	CHAN_BOND_SEQ_LEN => 1,
	
--Clock Correction	
	CLK_CORRECT_USE => FALSE,
	CLK_COR_8B10B_DE => TRUE,
	CLK_COR_MAX_LAT => 44,
	CLK_COR_MIN_LAT => 36,
	CLK_COR_SEQ_1_1 => "00010111100",
	CLK_COR_SEQ_1_2 => "00010111100",
	CLK_COR_SEQ_1_3 => "00010111100",
	CLK_COR_SEQ_1_4 => "00010111100",
	CLK_COR_SEQ_1_MASK => "0000",
	CLK_COR_SEQ_2_1 => "00010111100",
	CLK_COR_SEQ_2_2 => "00010111100",
	CLK_COR_SEQ_2_3 => "00010111100",
	CLK_COR_SEQ_2_4 => "00010111100",
	CLK_COR_SEQ_2_MASK => "0000",
	CLK_COR_SEQ_2_USE => FALSE,
	CLK_COR_SEQ_LEN => 1,
	CLK_COR_SEQ_DROP => FALSE,
	
--Allignment	
	ALIGN_COMMA_WORD => 1,
	COMMA32 => FALSE,
	COMMA_10B_MASK => x"3FF",
	DEC_MCOMMA_DETECT => FALSE,
	DEC_PCOMMA_DETECT => FALSE,
	DEC_VALID_COMMA_ONLY => FALSE,
	MCOMMA_DETECT => FALSE,
	MCOMMA_32B_VALUE => x"000000F6",
	PCS_BIT_SLIP => FALSE,
	PCOMMA_DETECT => FALSE,
	PCOMMA_32B_VALUE => x"F6F62828",
	
--64b/66b	
	SH_CNT_MAX => 64,
	SH_INVALID_CNT_MAX => 16,

--Clocks
	RXCLK0_FORCE_PMACLK => TRUE,
	RX_CLOCK_DIVIDER => "10",
	RXASYNCDIVIDE => "00",
	RXUSRDIVISOR => 1,
	TXCLK0_FORCE_PMACLK => TRUE,
	TX_CLOCK_DIVIDER => "10",
	TXASYNCDIVIDE => "00",

--Buffer
	RX_BUFFER_USE => TRUE,
	TX_BUFFER_USE => TRUE,

-------------------------MGT Digital Receiver Attributes -------------------------
	DCDR_FILTER => "000",
	DIGRX_FWDCLK => "10",
	DIGRX_SYNC_MODE => FALSE,
	ENABLE_DCDR => FALSE,
	REPEATER => FALSE,
	RXBY_32 => TRUE,
	RXDIGRX => FALSE,
	SAMPLE_8X => TRUE,
	RXDIGRESET => FALSE,

------------------------MGT Tile Communication Attributes-------------------------
	GT11_MODE => "SINGLE",
	
------------------------Data Path Attributes---------------------------------	
	TXDATA_SEL => "00",
	RXDATA_SEL => "00",

------------------------PLL Attributes---------------------------------	
	RXLOOPFILT => "1111",
	RXCPSEL => TRUE,
	RXCTRL1 => x"200",
	RXVCO_CTRL_ENABLE => TRUE,
	RXAPD => FALSE,
	TXLOOPFILT => "1111",
	TXCPSEL => TRUE,
	TXCTRL1 => x"200",
	VCO_CTRL_ENABLE => TRUE,

------------------------Reserved Attributes---------------------------------	
	RXSLOWDOWN_CAL => "00",
	CYCLE_LIMIT_SEL => "00",
	SLOWDOWN_CAL => "00",
	POWER_ENABLE => TRUE,
	OPPOSITE_SELECT => FALSE,
	RXCYCLE_LIMIT_SEL => "00",
	PMAVBGCTRL => "00000",
	BANDGAPSEL => FALSE,
	PMAIREFTRIM => "0111",
	IREFBIASMODE => "11",
	BIASRESSEL => FALSE,
	PMAVREFTRIM => "0111",
	VREFBIASMODE => "11",
	PMACLKENABLE => TRUE,
	RXLB => FALSE,
	RXFETUNE => "01",
	RXRCPADJ => "010",
	RXRIBADJ => "11",
	RXCMADJ => "10",
	TXPRE_PRDRV_DAC => "111",
	TXPOST_PRDRV_DAC => "000",
	TXDAT_PRDRV_DAC => "111",
	RXFECONTROL2 => "000",
	RXCPTST => FALSE,
	RXPDDTST => TRUE,
	RXACTST => FALSE,
	RXAFETST => FALSE,
	RXFECONTROL1 => "00",
	RXLKAPD => FALSE,
	RXRCPPD => FALSE,
	RXRPDPD => FALSE,
	RXAFEPD => FALSE,
	TXAPD => FALSE,
	TXLVLSHFTPD => FALSE,
	TXDIGPD => FALSE,
	TXAREFBIASSEL => TRUE)
---------------------port map ----------------------------------------------------------
 port map (
      
  --CRC Primitive Ports

	RXCRCCLK => '0',
	RXCRCDATAVALID => '0',
	RXCRCDATAWIDTH(2 downto 0) => "000",
	RXCRCIN(63 downto 0) => x"0000000000000000",
	RXCRCINIT => '0',
	RXCRCINTCLK => '0',
	RXCRCPD => '0',
	RXCRCRESET => '1',
	RXCRCOUT(31 downto 0) => open,
	TXCRCCLK => '0',
	TXCRCDATAVALID => '0',
	TXCRCDATAWIDTH(2 downto 0) => "000",
	TXCRCIN(63 downto 0) => x"0000000000000000",
	TXCRCINIT => '0',
	TXCRCINTCLK => '0',
	TXCRCPD => '0',
	TXCRCRESET => '1',
	TXCRCOUT(31 downto 0) => open,
	
----------------------PMA Primitive Ports-----------------------	
--calibration
	RXCALFAIL => open,
	RXCLKSTABLE => '1',
	RXCYCLELIMIT => open,
	TXCALFAIL => open,
	TXCLKSTABLE => '1',
	TXCYCLELIMIT => open,
	
--Driver/Buffers
	TXINHIBIT => '0',
	RXPOLARITY => '0',
	TXPOLARITY => '0',
 	RX1N =>  RX1N_IN,
 	RX1P =>  RX1P_IN,
	TX1N => TX1N_OUT,
	TX1P => TX1P_OUT,
	
--Clocks/Clock Status
	RXLOCK => open,
	RXPMARESET => '0',
	RXRECCLK1 => RXRECCLK1_OUT,
	RXRECCLK2 => open,
	RXMCLK => open,
	TXLOCK => open,
	TXOUTCLK1 => TXOUTCLK1_OUT,
	TXOUTCLK2 => TXOUTCLK2_OUT,
	TXPMARESET => '0',
	TXPCSHCLKOUT => open,
	RXPCSHCLKOUT => open,
	
--Special Signals	
	RXSIGDET => open,
	RXSYNC => '0',
	TXENOOB => '0',
	TXSYNC => '0',
                           
--------------------------PCS Primitive Ports------------------------

--channel bonding 
	CHBONDI(4 downto 0) => "00000",
	CHBONDO => open,
	ENCHANSYNC => '0',

--64B/66B
	RXBLOCKSYNC64B66BUSE => '0',
	RXDEC64B66BUSE => '0',
	RXDESCRAM64B66BUSE => '0',
	RXIGNOREBTF => '0',
	TXENC64B66BUSE => '0',
	TXGEARBOX64B66BUSE => '0',
	TXSCRAM64B66BUSE => '0',
	
--8B/10B	
	RXCHARISK(7 downto 0) => open,
	RXCHARISCOMMA(7 downto 0) => open,
	RXDEC8B10BUSE => '0',
	RXDISPERR(7 downto 0) => open,
	RXNOTINTABLE(7 downto 0)=>open,
	RXRUNDISP(7 downto 0) => open,
 
	TXBYPASS8B10B => "11111111",
 
	TXCHARDISPMODE(7 downto 1) => "0000000",
	TXCHARDISPMODE(0) => TXDATA_IN(9),
	TXCHARDISPVAL(7 downto 1) => "0000000",
	TXCHARDISPVAL(0) => TXDATA_IN(8),
	TXCHARISK(7 downto 0) => "00000000",
	TXENC8B10BUSE => '0',
	TXKERR(7 downto 0) => open,
	TXRUNDISP(7 downto 0) => open,
	
--Alignment
	ENMCOMMAALIGN => '1',
	ENPCOMMAALIGN => '1',
	RXCOMMADET => open,
	RXCOMMADETUSE => '0',
	RXLOSSOFSYNC(1 downto 0) => open,
	RXREALIGN => open,
	RXSLIDE => '0',
	
--Data Path
    RXDATA(63 downto 8) => RXDATA_OUT_FLOAT(63 downto 8),
    RXDATA(7 downto 0) => RXDATA_OUT(7 downto 0),
    TXDATA(63 downto 8) => x"00000000000000",
    TXDATA(7 downto 0) => TXDATA_IN(7 downto 0),
    RXDATAWIDTH(1) => '0',
    RXDATAWIDTH(0) => '0',
	RXINTDATAWIDTH(1) => '1',
	RXINTDATAWIDTH(0) => '0',
	TXDATAWIDTH(1) => '0',
    TXDATAWIDTH(0) => '0',
	TXINTDATAWIDTH(1) => '1',
	TXINTDATAWIDTH(0) => '1',
	
--Status/Clocks              
	RXBUFERR => open,
	RXRESET => '0',
	RXSTATUS(5 downto 0) => open,
	RXUSRCLK => '0',
	RXUSRCLK2 => RXUSRCLK2_IN,
	TXBUFERR => open,
	TXRESET => '0',
	TXUSRCLK => TXUSRCLK_IN,
	TXUSRCLK2 => TXUSRCLK2_IN,
	
--Global SIgnal Primitive Ports
	LOOPBACK(1 downto 0) => "00",
	POWERDOWN => '0',
	GREFCLK => GREFCLK_IN,
	REFCLK1 => '0',--REFCLK1_IN,
	REFCLK2 => '0',
	
--Configuration Primitive Ports	
	DADDR(7 downto 0) => "00000000",
	DCLK => '0',
	DEN => '0',
	DI(15 downto 0) => "0000000000000000",
	DO(15 downto 0) => open,
	DRDY => open,
	DWE => '0',
	COMBUSOUT(15 downto 0) => open,
	COMBUSIN(15 downto 0) => "0000000000000000"
	);

--
--   GT11B_CUSTOM_INST : GT11
--   --INST_GT11 : GT11
--	generic map( 
--   
----------------RocketIO MGT CRC Attributes-------------
--	RXCRCCLOCKDOUBLE => FALSE,
--	RXCRCINITVAL => x"FFFFFFFF",
--	RXCRCSAMECLOCK => FALSE,
--	TXCRCCLOCKDOUBLE => FALSE,
--	TXCRCINITVAL => x"FFFFFFFF",
--	TXCRCSAMECLOCK => FALSE,
--	RXCRCENABLE => FALSE,
--	RXCRCINVERTGEN => FALSE,
--	TXCRCENABLE => FALSE,
--	TXCRCINVERTGEN => FALSE,
--	
-----------------RocketIO MGT PMA Attributes-------------	
--	FDET_LCK_SEL => "001",
--	FDET_HYS_SEL => "100",
--	FDET_LCK_CAL => "100",
--	FDET_HYS_CAL => "010",
--	VCODAC_INIT => "0000000000",
--	TXFDCAL_CLOCK_DIVIDE =>  "NONE",
--	LOOPCAL_WAIT => "00",
--	RXFDET_LCK_SEL => "111",
--	RXFDET_HYS_SEL => "001",
--	RXFDET_LCK_CAL => "101",
--	RXFDET_HYS_CAL => "010",
--	RXVCODAC_INIT => "0001000001",
--	RXFDCAL_CLOCK_DIVIDE => "TWO",
--	RXLOOPCAL_WAIT => "00",
--	
-----------------Drivers/Buffers--------------------------	
--	RXAFEEQ => "000000000",
--	RXDCCOUPLE => FALSE,
--	RXEQ => x"4000000000000000",
--	TXDAT_TAP_DAC => "10000",
--	TXPOST_TAP_DAC => "00111",
--	TXHIGHSIGNALEN => TRUE,
--	TXPOST_TAP_PD => TRUE,
--	TXPRE_TAP_DAC => "00000",
--	TXPRE_TAP_PD => TRUE,
--	TXSLEWRATE => FALSE,
--	TXTERMTRIM => "1100",
--	
-----------------Clocks----------------------------------	
--	RXCLKMODE => "100111",
--	RXOUTDIV2SEL => 2,
--	RXPLLNDIVSEL => 8,
--	RXPMACLKSEL => "GREFCLK", --REFCLK1
--	RXRECCLK1_USE_SYNC => FALSE,
--	TXABPMACLKSEL => "GREFCLK",
--	TXCLKMODE => "0100",
--	TXOUTCLK1_USE_SYNC => FALSE,
--	TXOUTDIV2SEL => 8,
--	TXPHASESEL => FALSE,
--	TXPLLNDIVSEL => 40,
--	
------------------Miscellaneous-------------------------	
--	RXCDRLOS => "000000",
--	RXLKADJ => "00000",
--	RXPD => FALSE,
--	RXRSDPD => FALSE,
--	TXPD => FALSE,
--	PMACOREPWRENABLE => TRUE,
--	PMA_BIT_SLIP => FALSE,
--	
----------------MGT PCS Attributes----------------------	
----Channel Bonding
--	CCCB_ARBITRATOR_DISABLE => FALSE,
--	CHAN_BOND_LIMIT => 16,
--	CHAN_BOND_MODE => "NONE",
--	CHAN_BOND_ONE_SHOT => FALSE,
--	CHAN_BOND_SEQ_1_1 => "00000000000",
--	CHAN_BOND_SEQ_1_2 => "00000000000",
--	CHAN_BOND_SEQ_1_3 => "00000000000",
--	CHAN_BOND_SEQ_1_4 => "00000000000",
--	CHAN_BOND_SEQ_1_MASK => "1110",
--	CHAN_BOND_SEQ_2_1 => "00000000000",
--	CHAN_BOND_SEQ_2_2 => "00000000000",
--	CHAN_BOND_SEQ_2_3 => "00000000000",
--	CHAN_BOND_SEQ_2_4 => "00000000000",
--	CHAN_BOND_SEQ_2_MASK => "1110",
--	CHAN_BOND_SEQ_2_USE => FALSE,
--	CHAN_BOND_SEQ_LEN => 1,
--	
----Clock Correction	
--	CLK_CORRECT_USE => FALSE,
--	CLK_COR_8B10B_DE => TRUE,
--	CLK_COR_MAX_LAT => 44,
--	CLK_COR_MIN_LAT => 36,
--	CLK_COR_SEQ_1_1 => "00010111100",
--	CLK_COR_SEQ_1_2 => "00010111100",
--	CLK_COR_SEQ_1_3 => "00010111100",
--	CLK_COR_SEQ_1_4 => "00010111100",
--	CLK_COR_SEQ_1_MASK => "0000",
--	CLK_COR_SEQ_2_1 => "00010111100",
--	CLK_COR_SEQ_2_2 => "00010111100",
--	CLK_COR_SEQ_2_3 => "00010111100",
--	CLK_COR_SEQ_2_4 => "00010111100",
--	CLK_COR_SEQ_2_MASK => "0000",
--	CLK_COR_SEQ_2_USE => FALSE,
--	CLK_COR_SEQ_LEN => 1,
--	CLK_COR_SEQ_DROP => FALSE,
--	
----Allignment	
--	ALIGN_COMMA_WORD => 1,
--	COMMA32 => FALSE,
--	COMMA_10B_MASK => x"3FF",
--	DEC_MCOMMA_DETECT => FALSE,
--	DEC_PCOMMA_DETECT => FALSE,
--	DEC_VALID_COMMA_ONLY => FALSE,
--	MCOMMA_DETECT => FALSE,
--	MCOMMA_32B_VALUE => x"000000F6",
--	PCS_BIT_SLIP => FALSE,
--	PCOMMA_DETECT => FALSE,
--	PCOMMA_32B_VALUE => x"F6F62828",
--	
----64b/66b	
--	SH_CNT_MAX => 64,
--	SH_INVALID_CNT_MAX => 16,
--
----Clocks
--	RXCLK0_FORCE_PMACLK => TRUE,
--	RX_CLOCK_DIVIDER => "10",
--	RXASYNCDIVIDE => "00",
--	RXUSRDIVISOR => 1,
--	TXCLK0_FORCE_PMACLK => TRUE,
--	TX_CLOCK_DIVIDER => "10",
--	TXASYNCDIVIDE => "00",
--
----Buffer
--	RX_BUFFER_USE => TRUE,
--	TX_BUFFER_USE => TRUE,
--
---------------------------MGT Digital Receiver Attributes -------------------------
--	DCDR_FILTER => "000",
--	DIGRX_FWDCLK => "10",
--	DIGRX_SYNC_MODE => FALSE,
--	ENABLE_DCDR => FALSE,
--	REPEATER => FALSE,
--	RXBY_32 => TRUE,
--	RXDIGRX => FALSE,
--	SAMPLE_8X => TRUE,
--	RXDIGRESET => FALSE,
--
--------------------------MGT Tile Communication Attributes-------------------------
--	GT11_MODE => "SINGLE",
--	
--------------------------Data Path Attributes---------------------------------	
--	TXDATA_SEL => "00",
--	RXDATA_SEL => "00",
--
--------------------------PLL Attributes---------------------------------	
--	RXLOOPFILT => "1111",
--	RXCPSEL => TRUE,
--	RXCTRL1 => x"200",
--	RXVCO_CTRL_ENABLE => TRUE,
--	RXAPD => FALSE,
--	TXLOOPFILT => "1111",
--	TXCPSEL => TRUE,
--	TXCTRL1 => x"200",
--	VCO_CTRL_ENABLE => TRUE,
--
--------------------------Reserved Attributes---------------------------------	
--	RXSLOWDOWN_CAL => "00",
--	CYCLE_LIMIT_SEL => "00",
--	SLOWDOWN_CAL => "00",
--	POWER_ENABLE => TRUE,
--	OPPOSITE_SELECT => FALSE,
--	RXCYCLE_LIMIT_SEL => "00",
--	PMAVBGCTRL => "00000",
--	BANDGAPSEL => FALSE,
--	PMAIREFTRIM => "0111",
--	IREFBIASMODE => "11",
--	BIASRESSEL => FALSE,
--	PMAVREFTRIM => "0111",
--	VREFBIASMODE => "11",
--	PMACLKENABLE => TRUE,
--	RXLB => FALSE,
--	RXFETUNE => "01",
--	RXRCPADJ => "010",
--	RXRIBADJ => "11",
--	RXCMADJ => "10",
--	TXPRE_PRDRV_DAC => "111",
--	TXPOST_PRDRV_DAC => "000",
--	TXDAT_PRDRV_DAC => "111",
--	RXFECONTROL2 => "000",
--	RXCPTST => FALSE,
--	RXPDDTST => TRUE,
--	RXACTST => FALSE,
--	RXAFETST => FALSE,
--	RXFECONTROL1 => "00",
--	RXLKAPD => FALSE,
--	RXRCPPD => FALSE,
--	RXRPDPD => FALSE,
--	RXAFEPD => FALSE,
--	TXAPD => FALSE,
--	TXLVLSHFTPD => FALSE,
--	TXDIGPD => FALSE,
--	TXAREFBIASSEL => TRUE)
-----------------------port map ----------------------------------------------------------
-- port map (
--      
--  --CRC Primitive Ports
--
--	RXCRCCLK => '0',
--	RXCRCDATAVALID => '0',
--	RXCRCDATAWIDTH(2 downto 0) => "000",
--	RXCRCIN(63 downto 0) => x"0000000000000000",
--	RXCRCINIT => '0',
--	RXCRCINTCLK => '0',
--	RXCRCPD => '0',
--	RXCRCRESET => '1',
--	RXCRCOUT(31 downto 0) => open,
--	TXCRCCLK => '0',
--	TXCRCDATAVALID => '0',
--	TXCRCDATAWIDTH(2 downto 0) => "000",
--	TXCRCIN(63 downto 0) => x"0000000000000000",
--	TXCRCINIT => '0',
--	TXCRCINTCLK => '0',
--	TXCRCPD => '0',
--	TXCRCRESET => '1',
--	TXCRCOUT(31 downto 0) => open,
--	
------------------------PMA Primitive Ports-----------------------	
----calibration
--	RXCALFAIL => open,
--	RXCLKSTABLE => '1',
--	RXCYCLELIMIT => open,
--	TXCALFAIL => open,
--	TXCLKSTABLE => '1',
--	TXCYCLELIMIT => open,
--	
----Driver/Buffers
--	TXINHIBIT => '0',
--	RXPOLARITY => '0',
--	TXPOLARITY => '0',
-- 	RX1N =>  RX1N_IN,
-- 	RX1P =>  RX1P_IN,
--	TX1N => TX1N_OUT,
--	TX1P => TX1P_OUT,
--	
----Clocks/Clock Status
--	RXLOCK => open,
--	RXPMARESET => '0',
--	RXRECCLK1 => RXRECCLK1_OUT,
--	RXRECCLK2 => open,
--	RXMCLK => open,
--	TXLOCK => open,
--	TXOUTCLK1 => TXOUTCLK1_OUT,
--	TXOUTCLK2 => TXOUTCLK2_OUT,
--	TXPMARESET => '0',
--	TXPCSHCLKOUT => open,
--	RXPCSHCLKOUT => open,
--	
----Special Signals	
--	RXSIGDET => open,
--	RXSYNC => '0',
--	TXENOOB => '0',
--	TXSYNC => '0',
--                           
----------------------------PCS Primitive Ports------------------------
--
----channel bonding 
--	CHBONDI(4 downto 0) => "00000",
--	CHBONDO => open,
--	ENCHANSYNC => '0',
--
----64B/66B
--	RXBLOCKSYNC64B66BUSE => '0',
--	RXDEC64B66BUSE => '0',
--	RXDESCRAM64B66BUSE => '0',
--	RXIGNOREBTF => '0',
--	TXENC64B66BUSE => '0',
--	TXGEARBOX64B66BUSE => '0',
--	TXSCRAM64B66BUSE => '0',
--	
----8B/10B	
--	RXCHARISK(7 downto 0) => open,
--	RXCHARISCOMMA(7 downto 0) => open,
--	RXDEC8B10BUSE => '0',
--	RXDISPERR(7 downto 0) => open,
--	RXNOTINTABLE(7 downto 0)=>open,
--	RXRUNDISP(7 downto 0) => open,
-- 
--	TXBYPASS8B10B => "11111111",
-- 
--	TXCHARDISPMODE(7 downto 1) => "0000000",
--	TXCHARDISPMODE(0) => TXDATA_IN(9),
--	TXCHARDISPVAL(7 downto 1) => "0000000",
--	TXCHARDISPVAL(0) => TXDATA_IN(8),
--	TXCHARISK(7 downto 0) => "00000000",
--	TXENC8B10BUSE => '0',
--	TXKERR(7 downto 0) => open,
--	TXRUNDISP(7 downto 0) => open,
--	
----Alignment
--	ENMCOMMAALIGN => '1',
--	ENPCOMMAALIGN => '1',
--	RXCOMMADET => open,
--	RXCOMMADETUSE => '0',
--	RXLOSSOFSYNC(1 downto 0) => open,
--	RXREALIGN => open,
--	RXSLIDE => '0',
--	
----Data Path
--    RXDATA(63 downto 8) => RXDATA_OUT_FLOAT(63 downto 8),
--    RXDATA(7 downto 0) => RXDATA_OUT(7 downto 0),
--    TXDATA(63 downto 8) => x"00000000000000",
--    TXDATA(7 downto 0) => TXDATA_IN(7 downto 0),
--    RXDATAWIDTH(1) => '0',
--    RXDATAWIDTH(0) => '0',
--	RXINTDATAWIDTH(1) => '1',
--	RXINTDATAWIDTH(0) => '0',
--	TXDATAWIDTH(1) => '0',
--    TXDATAWIDTH(0) => '0',
--	TXINTDATAWIDTH(1) => '1',
--	TXINTDATAWIDTH(0) => '1',
--	
----Status/Clocks              
--	RXBUFERR => open,
--	RXRESET => '0',
--	RXSTATUS(5 downto 0) => open,
--	RXUSRCLK => '0',
--	RXUSRCLK2 => RXUSRCLK2_IN,
--	TXBUFERR => open,
--	TXRESET => '0',
--	TXUSRCLK => TXUSRCLK_IN,
--	TXUSRCLK2 => TXUSRCLK2_IN,
--	
----Global SIgnal Primitive Ports
--	LOOPBACK(1 downto 0) => "00",
--	POWERDOWN => '0',
--	GREFCLK => GREFCLK_IN,
--	REFCLK1 => '0',--REFCLK1_IN,
--	REFCLK2 => '0',
--	
----Configuration Primitive Ports	
--	DADDR(7 downto 0) => "00000000",
--	DCLK => '0',
--	DEN => '0',
--	DI(15 downto 0) => "0000000000000000",
--	DO(15 downto 0) => open,
--	DRDY => open,
--	DWE => '0',
--	COMBUSOUT(15 downto 0) => open,
--	COMBUSIN(15 downto 0) => "0000000000000000"
--	);   
end BEHAVIORAL;


 
