extern int TimeClockTotalTest(int TestNo);
extern int Clock_VITCTest(int TVSystem);
extern int Clock_LTCTest(int TVSystem);
extern int Clock_1HzTest(int mode);
extern int CheckRAMBatteryStatus (int testmode);
extern char *ReadClockKUNumber (void);
extern char *ReadClockProdDate (void);
extern char *ReadClockCalDate (void);
extern char *ReadClockPTNo (void);
extern char *ReadClockSWVer (void);
