# @(#)makefile	1.9
#------------------------------------------------------------------------------
# Makefile for building all examples.
# 
# Please see the file readme.txt for more information
#------------------------------------------------------------------------------

PATH = $(PRODDIR)\bin;$PATH
			    export PATH

.DONE:
		@pause

C_ALL	= $(exist c c.all)		# Dhrystone example only included
C_CLN	= $(exist c c.clean)		#	 in C compiler package

ASM_ALL = $(exist asm asm.all)		# asm example only included in
ASM_CLN = $(exist asm asm.clean)	#	C compiler and ASM package

XVW_ALL	= $(exist xvw xvw.all)		# xvw example only included in
XVW_CLN	= $(exist xvw xvw.clean)	#	CrossView Package

all	:   $(C_ALL) $(ASM_ALL) $(XVW_ALL)
	    @echo "Building examples is finished"	

clean	:   $(C_CLN) $(ASM_CLN) $(XVW_CLN)
	    @echo "Cleanup of examples is finished"


#
# all rules for examples included in the C compiler package
#

c.all	:
	$(MAKE) -G c
	$(MAKE) -G io
	$(MAKE) -G dhry
	$(MAKE) -G fpsigfpe
	$(MAKE) -G fptrap
	$(MAKE) -G whet
	$(MAKE) -G sieve

c.clean	:
	$(MAKE) -G c clean
	$(MAKE) -G io clean
	$(MAKE) -G dhry clean
	$(MAKE) -G fpsigfpe clean
	$(MAKE) -G fptrap clean
	$(MAKE) -G whet clean
	$(MAKE) -G sieve clean

#
# all rules for examples included both in the assembler and 
# C compiler package
#

asm.all	:
	$(MAKE) -G asm

asm.clean:
	$(MAKE) -G asm clean


#
# all rules for examples included in the CrossView package
#

xvw.all	:
	$(MAKE) -G xvw

xvw.clean:
	$(MAKE) -G xvw clean


