.AUTODEPEND

#		*Translator Definitions*
CC = c:\xa\bin\xac
ASM = c:\xa\bin\xac
LINK = c:\xa\bin\xac -A0,20,5000 -BIN -CRxref -PSECTMAP


#		*Implicit Rules*
.c.obj:
  $(CC)  $<  -Zg -C -Bs

.as.obj:
   $(ASM) $< -O -Zg -C

#		*Explicit Rules*

ud.b: mas.obj uiic.obj
      $(LINK) mas.obj piic.obj


#		*Individual File Dependencies*
mas.obj:	mas.c vars.c
piic.obj:	piic.c vars.c

