
# Makefile for rgb2   project

DEBUG=0

!if$(DEBUG)
CFLAGS = -c -K -v
LFLAGS = /x /v
AFLAGS = /zi
!else
CFLAGS = -c -K
LFLAGS = /x
AFLAGS =
!endif

CC = c:\tc\tcc
LN = c:\tc\tlink

LIBS = C:\tc\LIB\mathS.lib C:\tc\LIB\CS.lib C:\tc\LIB\emu.lib
START = C:\tc\LIB\C0S.obj

.c.obj:
      $(CC) $(CFLAGS) $&.c

OBJECTS = rgb2.obj xcom.obj

rgb2.exe: $(OBJECTS)
  $(LN) $(LFLAGS) $(START) $(OBJECTS),$<,,$(LIBS)
#  $(LN) @linkresp

rgb2.obj: rgb2.c
#iic_drv.obj: iic_drv.c
xcom.obj: xcom.c port.h

