
# Makefile for USB_MAIN PROJECT 

AFLAGS = NOPRINT

#CFLAGS = DB OE CD OPTIMIZE(9,SPEED) SMALL
CFLAGS = DB OE NOPR SMALL

AA51= c:\Cygnal\IDEfiles\c51\Bin\a51
CC51= c:\Cygnal\IDEfiles\c51\Bin\c51
LN51= c:\Cygnal\IDEfiles\c51\Bin\bl51

.c.obj:
      $(CC51) $&.c $(CFLAGS)

.a51.obj:
      $(AA51) $&.a51 $(AFLAGS)


a.abs: USB_MAIN.obj uart.OBJ

   del a.m51
   $(LN51) @LINK.RSP
   c:\Cygnal\IDEfiles\c51\Bin\OH51 a.abs
   HB80 a.hex usb_main.bin

USB_MAIN.obj: USB_MAIN.c
uart.OBJ:     uart.C


