[COREGEN.VERILOG Component Instantiation.mathtest]
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="mathtest YourInstanceName ("
text007="    .dividend(dividend),"
text008="    .divisor(divisor),"
text009="    .quot(quot),"
text010="    .remd(remd),"
text011="    .clk(clk),"
text012="    .rfd(rfd),"
text013="    .aclr(aclr),"
text014="    .sclr(sclr),"
text015="    .ce(ce));"
text016=""
text017=" "
type=template
[COREGEN.VHDL Component Instantiation.mathtest]
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component mathtest"
text005="    port ("
text006="    dividend: IN std_logic_VECTOR(31 downto 0);"
text007="    divisor: IN std_logic_VECTOR(31 downto 0);"
text008="    quot: OUT std_logic_VECTOR(31 downto 0);"
text009="    remd: OUT std_logic_VECTOR(31 downto 0);"
text010="    clk: IN std_logic;"
text011="    rfd: OUT std_logic;"
text012="    aclr: IN std_logic;"
text013="    sclr: IN std_logic;"
text014="    ce: IN std_logic);"
text015="end component;"
text016=""
text017=""
text018=""
text019=" "
text020="-------------------------------------------------------------"
text021=" "
text022="-- The following code must appear in the VHDL architecture body."
text023="-- Substitute your own instance name and net names."
text024=" "
text025="your_instance_name : mathtest"
text026="        port map ("
text027="            dividend => dividend,"
text028="            divisor => divisor,"
text029="            quot => quot,"
text030="            remd => remd,"
text031="            clk => clk,"
text032="            rfd => rfd,"
text033="            aclr => aclr,"
text034="            sclr => sclr,"
text035="            ce => ce);"
text036=" "
type=template
