/****************************************************************************/
/* MODULE:                                                                  */
/*   keyscan.h - Keyscan	 					    										 								*/
/****************************************************************************/
/* FUNCTIONS:                                                               */
/*                                                                          */
/*                                                                          */
/* TASKS:                                                                   */
/*                                                                          */
/*                                                                          */
/****************************************************************************/
/*
 *   PTV software for PT5201
 *   Copyright (c)
 *   ProTeleVision Technologies A/S.
 *   ALL RIGHTS RESERVED
*/
/****************************************************************************/
#ifndef _KEYSCAN_H
#define _KEYSCAN_H

extern void keyscan( void);
extern void keyscan_init( void);

#endif