/****************************************************************************/
/* MODULE:                                                                  */
/*   tables.h - Keyboard driver						    													 	  */
/****************************************************************************/
/* FUNCTIONS:                                                               */
/*                                                                          */
/*                                                                          */
/* TASKS:                                                                   */
/*                                                                          */
/*                                                                          */
/****************************************************************************/
/*
 *   PTV software for PT5201
 *   Copyright (c)
 *   ProTeleVision Technologies A/S.
 *   ALL RIGHTS RESERVED
*/
/****************************************************************************/

#ifndef _TABLES_H
#define _TABLES_H

#define ScHPhaseHigh	180
#define ScHPhaseLow		-179

enum TVSystems					{	PAL = 0, PAL_PALID, NTSC_US, NTSC_J}; 

#endif