
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 8.1 EDK_I.18.7
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xplbarb.h"

/*
* The configuration table for devices
*/

XPlbArb_Config XPlbArb_ConfigTable[] =
{
	{
		XPAR_PLB_DEVICE_ID,
		XPAR_PLB_BASEADDR,
		XPAR_PLB_PLB_NUM_MASTERS
	}
};


