.AUTODEPEND

#		*Translator Definitions*
CC = c:\c51\c51
ASM = c:\c51\a51
LINK = c:\c51\l51


#		*Implicit Rules*
.c.obj:
  $(CC)  $< small debug oe code symbols noprint

.a.obj:
   $(ASM) $< debug

#		*Explicit Rules*

time.m51: time.obj hint.obj wint.obj tab.obj
      $(LINK) @linker.dat


#		*Individual File Dependencies*
time.obj:	time.c time.h
tab.obj:	tab.c time.h
hint.obj:	hint.a
wint.obj:	wint.a
