# @(#)makefile	1.12 
#------------------------------------------------------------------------------
# Makefile for building the 'sieve' benchmark
#
# Make sure the bin directory is in your PATH environment. Then type:
#
#	mkxa
#
# Please read the file readme.txt for more information
#------------------------------------------------------------------------------

ALL		: sieve.abs

##
## definitions of configuration dependent options and controls
##

ifdef 		V
VERBOSE		= -v
endif

ifdef 		LARGE
SET_MODEL	= -Ml
SET_LIB		= -lcl -lfpl
else
SET_MODEL	= -Ms
SET_LIB		= -lcs -lfps
endif

ifdef SIZE
OPTIM		= -O1
else
OPTIM		= -O2
M_TIME		= -DMEASURE_TIME
OUTPUT		= -DPRINT
endif

CCFLAGS		= $(VERBOSE) $(SET_MODEL) $(M_TIME) $(OUTPUT) $(OPTIM) -g -Wc-w91
LDFLAGS		= $(VERBOSE) $(SET_MODEL) $(SET_LIB)

##
## the rules for building the example application
##

sieve.abs	: sieve.obj

sieve.obj	: sieve.c

clean		:
		$(exist sieve.abs del sieve.abs)
		$(exist sieve.sym del sieve.sym)
		$(exist sieve.map del sieve.map)
		$(exist sieve.obj del sieve.obj)
