[COREGEN.VERILOG Component Instantiation.ch_ram]
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="ch_ram YourInstanceName ("
text007="    .addra(addra),"
text008="    .addrb(addrb),"
text009="    .clka(clka),"
text010="    .clkb(clkb),"
text011="    .dina(dina),"
text012="    .doutb(doutb),"
text013="    .ena(ena),"
text014="    .enb(enb),"
text015="    .wea(wea));"
text016=""
text017=" "
type=template
[COREGEN.VERILOG Component Instantiation.color_rom]
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="color_rom YourInstanceName ("
text007="    .A(A),"
text008="    .CLK(CLK),"
text009="    .QSPO_CE(QSPO_CE),"
text010="    .QSPO(QSPO));"
text011=""
text012=" "
type=template
[COREGEN.VHDL Component Instantiation.ch_ram]
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component ch_ram"
text005="    port ("
text006="    addra: IN std_logic_VECTOR(8 downto 0);"
text007="    addrb: IN std_logic_VECTOR(8 downto 0);"
text008="    clka: IN std_logic;"
text009="    clkb: IN std_logic;"
text010="    dina: IN std_logic_VECTOR(7 downto 0);"
text011="    doutb: OUT std_logic_VECTOR(7 downto 0);"
text012="    ena: IN std_logic;"
text013="    enb: IN std_logic;"
text014="    wea: IN std_logic);"
text015="end component;"
text016=""
text017=""
text018=""
text019=" "
text020="-------------------------------------------------------------"
text021=" "
text022="-- The following code must appear in the VHDL architecture body."
text023="-- Substitute your own instance name and net names."
text024=" "
text025="your_instance_name : ch_ram"
text026="        port map ("
text027="            addra => addra,"
text028="            addrb => addrb,"
text029="            clka => clka,"
text030="            clkb => clkb,"
text031="            dina => dina,"
text032="            doutb => doutb,"
text033="            ena => ena,"
text034="            enb => enb,"
text035="            wea => wea);"
text036=" "
type=template
[COREGEN.VHDL Component Instantiation.color_rom]
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component color_rom"
text005="    port ("
text006="    A: IN std_logic_VECTOR(5 downto 0);"
text007="    CLK: IN std_logic;"
text008="    QSPO_CE: IN std_logic;"
text009="    QSPO: OUT std_logic_VECTOR(35 downto 0));"
text010="end component;"
text011=""
text012=""
text013=""
text014=" "
text015="-------------------------------------------------------------"
text016=" "
text017="-- The following code must appear in the VHDL architecture body."
text018="-- Substitute your own instance name and net names."
text019=" "
text020="your_instance_name : color_rom"
text021="        port map ("
text022="            A => A,"
text023="            CLK => CLK,"
text024="            QSPO_CE => QSPO_CE,"
text025="            QSPO => QSPO);"
text026=" "
type=template
