.AUTODEPEND

#		*Translator Definitions*
CC = c:\xa\bin\xac
ASM = c:\xa\bin\xac
LINK = c:\xa\bin\xac -A0,20,5000 -BIN -CRxref -PSECTMAP


#		*Implicit Rules*
.c.obj:
  $(CC)  $<  -Zg -C -Bs

.as.obj:
   $(ASM) $< -O -Zg -C

#		*Explicit Rules*

ud.b: sou.obj hint.obj tab.obj
      $(LINK) sou.obj hint.obj tab.obj


#		*Individual File Dependencies*
sou.obj:	sou.c vars.c
tab.obj:	tab.c vars.c
hint.obj:	hint.as
