@ECHO OFF
REM Calling chanpict.exe with appropriate codes for displaying the PAL-G
REM indian head test pattern.
REM -----------------------------------------------------------------------
REM
REM Author:         Mikael Nadelmann
REM
REM First created:  08/01/93
REM
REM New update:     08/01/93  Adding call.
REM New update:     30/03/93  Editing call.
REM
REM -----------------------------------------------------------------------


C:\PICTURE\UTILITY\chanpic2 NAS=702 NAL=486 XZ0=0 XZ1=31 XZ2=62 YZ0=0 YZ1=2 YZ2=4 XO0=141 YO0=1 Mode=2