/****************************************************************************/
/* MODULE:                                                                  */
/*   ext0drv.h - external interrupt 0 driver                                */
/****************************************************************************/
/* FUNCTIONS:                                                               */
/*                                                                          */
/*                                                                          */
/* TASKS:                                                                   */
/*                                                                          */
/*                                                                          */
/****************************************************************************/
/*
 *   PTV software for PT5201
 *   Copyright (c)
 *   ProTeleVision Technologies A/S.
 *   ALL RIGHTS RESERVED
*/
/****************************************************************************/

#ifndef _EXT0DRV_H
#define _EXT0DRV_H


#include "define.h"
#include "rtxcobj.h"

void ext0_init( void);

#endif


