/****************************************************************************/
/* MODULE:                                                                  */
/*   Front.h - Front enums                                                  */
/****************************************************************************/
/* FUNCTIONS:                                                               */
/*                                                                          */
/*                                                                          */
/* TASKS:                                                                   */
/*                                                                          */
/* NOTES:                                                                   */
/*                                                                          */
/****************************************************************************/
/*
 *   PTV software for PT5765    
 *   Copyright (c) 
 *   ProTeleVision Technologies A/S.
 *   ALL RIGHTS RESERVED
*/
/****************************************************************************/

#ifndef _FRONT_H
#define _FRONT_H


enum Inputs {
	Input_RF=0,
	Input_BaseBand
};

#endif