/***************************************************************************/
/*  Copyright PHILIPS TV TEST EQUIPMENT A/S, BRONDBY 1997             */
/*  Project:    PM5639 Display Unit                           */
/*  Module:   RUN.H                                     */
/*  Author:   Kim Engedahl, DEV                             */
/*  Org. date:  951017                                    */
/*  Rev. date:  970822 KEn  DEV                             */
/*  Status:   Version 2.3                                 */
/*                                                  */
/*  Changes:                                            */
/*  970822 Released as version 2.3                            */
/*  951207 Released as version 2.2                            */
/***************************************************************************/

extern void initall( unsigned char Poweron_Button);
extern void outxyy( void);
extern void outrgb( void);