
# Makefile for PT8642 PROJECT


# WL(1) means Lists only those warnings which may generate
#       incorrect code (Cx51 Compiler User's Guide, page 85)
#
# Linker controls: DISABLEWARNING
#                  A51/AX51/A251 Macro Assembler and Utilities
#                  page 307.

AFLAGS = NOPRINT
CFLAGS = DB OE NOPR WL(1) OPTIMIZE(9,SPEED) LARGE

AA51= c:\Cygnal\IDEfiles\c51\Bin\a51
CC51= c:\Cygnal\IDEfiles\c51\Bin\c51
LN51= c:\Cygnal\IDEfiles\c51\Bin\lx51

.c.obj:
      $(CC51) $&.c $(CFLAGS)

.a51.obj:
      $(AA51) $&.a51 $(AFLAGS)


a.hex: startup.obj cli.obj uart.obj mn_callback.obj mn_vars.obj netfinder.obj

   del a.m51
   del a.hex
   $(LN51) @LINKRSP
   c:\Cygnal\IDEfiles\c51\Bin\OHx51 a.abs
   HB80 a.hex a.bin

cli.obj:          cli.c mn_userconst.h
uart.obj:         uart.c uart.h
mn_callback.obj:  mn_callback.c mn_userconst.h
mn_vars.obj:      mn_vars.c mn_userconst.h
netfinder.obj:    netfinder.c
startup.obj:      startup.a51

