//-----------------------------------------------------------------------------
// netfinder.h
//-----------------------------------------------------------------------------
// Copyright 2006 Silicon Laboratories, Inc.
//
// Description:
//  This file contains user defined constants used by the TCP/IP Stack.
//
// Generated by TCP/IP Library Builder Version 3.23

//-----------------------------------------------------------------------------
// User Configurable Settings
//-----------------------------------------------------------------------------

#define NETFINDER_PORT        3040              // Defines the UDP port assigned
                                                // to the Netfinder protocol

// Customization Strings:
// These strings will be displayed on the front panel of the Netfinder 
// application. Add quotes ("") around the string, but do not add a semicolon
// at the end of the line. STRING_A and STRING_B describe the embedded system.
// STRING_C and STRING_D describe the first and second events.
#define STRING_A "Netfinder Device Name"
#define STRING_B "Enter Text Description"
#define STRING_C "Time Powered"
#define STRING_D "Time on Network"

//-----------------------------------------------------------------------------
// Function Prototypes
//-----------------------------------------------------------------------------
extern int netfinder_start(void);             
extern int netfinder_process_packet(void);
extern void netfinder_update_RTC(void);
extern void netfinder_reset_event1(void);
extern void netfinder_reset_event2(void);

//-----------------------------------------------------------------------------
// Global Variables
//-----------------------------------------------------------------------------
extern int netfinder_socketno;

