/****************************************************************************/
/* MODULE:                                                                  */
/*   rtcl_tdf.h - Controller & device independent type declarations         */
/****************************************************************************/
/*
 *   RTXCio    Version 1.4
 *   Copyright (c) 1993-1997.
 *   Embedded System Products, Inc.
 *   ALL RIGHTS RESERVED
*/
/****************************************************************************/
#ifndef _RTCL_TDF_H_  /* { _RTCL_TDF_H_ */
#define  _RTCL_TDF_H_

#ifdef __cplusplus /* { */
extern "C" {
#endif /* } __cplusplus */

typedef INT DEVID;                                /* Device identifier type */
typedef INT CNTLRID;                          /* Controller identifier type */
typedef INT SPFNCID;            /* Device special function indentifier type */

#ifdef __cplusplus /* { */
}
#endif /* } __cplusplus */

#endif    /* } _RTCL_TDF_H_ */

/* End of the RTCL_TDF.H module */
