
# Makefile for PT8640 PROJECT

AFLAGS = NOPRINT

CFLAGS = DB OE NOPR CD OPTIMIZE(9,SPEED) SMALL

AA51= c:\Cygnal\IDEfiles\c51\Bin\a51
CC51= c:\Cygnal\IDEfiles\c51\Bin\c51
LN51= c:\Cygnal\IDEfiles\c51\Bin\bl51

.c.obj:
      $(CC51) $&.c $(CFLAGS)

.a51.obj:
      $(AA51) $&.a51 $(AFLAGS)


a.abs: PT8640.obj RS232.obj spi_mod1.OBJ eeprom.obj

   del a.m51
   $(LN51) @LINKRSP
   c:\Cygnal\IDEfiles\c51\Bin\OH51 a.abs
   HB80 a.hex a.bin

PT8640.obj:   PT8640.c
RS232.obj:    RS232.c
spi_mod1.OBJ: spi_mod1.C
eeprom.obj:   eeprom.c


