# @(#)makefile	1.8 9/19/97
#-------------------------------------------------------------------------------
# Makefile for building the 'asm' example program.
#
# Make sure the bin directory is in your PATH environment. Then type:
#
#  	mkxa
#
# Please read the file readme.txt for more information
#-------------------------------------------------------------------------------

ALL		: calc.abs

##
## definitions of configuration dependent options and controls
##

ifdef V
VERBOSE		= -v
endif

##
## the rules for building the example application
##

calc.abs	: calc.obj startup.obj initseg.obj
	ccxa $(VERBOSE) -nolib $!

calc.obj	: calc.src
	ccxa -c -Wa-ga -l $(VERBOSE) $!

startup.obj	: startup.src
	ccxa -c -Wa-ga -l $(VERBOSE) $!

initseg.obj	: initseg.src
	ccxa -c -Wa-ga -l $(VERBOSE) $!


clean:
	$(exist calc.abs del calc.abs)
	$(exist calc.sym del calc.sym)
	$(exist calc.map del calc.map)
	$(exist calc.obj del calc.obj)
	$(exist initseg.obj del initseg.obj)
	$(exist startup.obj del startup.obj)
