/***************************************************************************/
/*	Copyright PHILIPS TV TEST EQUIPMENT A/S, BRONDBY 1997							*/
/*	Project:		PT8602/3 SDI Digital test signal generator						*/
/*	Module:		D1UTIL.H																		*/
/*	Author:		Kim Engedahl, DEV															*/
/*	Org. date:	960614																		*/
/*	Rev. date:	970512, KEn DEV															*/
/*	Status:		Version 1.0																	*/
/*																									*/
/*	Changes:																						*/
/***************************************************************************/

extern void Copy_TextRAM();
extern void Copy_SoundRAM();
extern void Wait10ms();
