/***************************************************************************/
/*  Copyright PHILIPS TV TEST EQUIPMENT A/S, BRONDBY 1997                  */
/*  Project:    PT860 SDI Digital test signal generator                    */
/*  Module:    VERSION.H                                                   */
/*  Author:    Kim Engedahl, DEV                                           */
/*  Org. date:  970507                                                     */
/*  Rev. date:  990614, KEn DEV                                            */
/*  Status:    Version 1.3                                                 */
/*                                                                         */
/*  Changes:                                                               */
/* 990614: Support for Text positioning in ver. 3.7                        */
/* 990308: Renamed some variables                                          */
/* 990302: New SW version                                                  */
/* 980929: Added new parameters.                                           */
/* 020630: Version with moving text: ver 3.8, 910 JK                       */
/***************************************************************************/

#define SWVersion      38    // Software version
#define HWType         03    // Hardware version: 03=PT8603
#define HWVersion      10    // 900 version: 0=Normal, 1,2,.. = 901,902,..
#define HWUserPattern  0    //
#define HWInformation  0    //
