HALOGEN LAMP CONTROL                          Revised:   January 21, 1993
7108 100 73291                                Revision: 

PHILIPS TV TEST EQUIPMENT





Bill Of Materials            January 21, 1993     13:09:17          Page    1

 Item  Quantity  Reference                 Part                                     
____________________________________________________________________________________

    1       6    C1,C2,C3,C4,C7,C9         100n    2222 370 11104    CK06           
    2       1    C5                        100u/35v    2222 116 50101    ELCO       
    3       2    C6,C10                    3300u/40v    2222 051 57332    ELCO3300  
    4       1    C8                        22n    2222 370 21223    CK06            
    5       1    D1                        KBU4    4008 102 60180    KBU4           
    6       1    D2                        BAW62    9331 012 20113    DIODE         
    7       6    H1,H2,H3,H4,H5,H6         MHOLE33        MHOLE33                   
    8       1    Q1                        BD237    9331 770 50112    TO220         
    9       5    R1,R2,R3,R4,R5            1R    2322 156 11008    RL05             
   10       2    R6,R7                     475R    2322 156 14751    RL05           
   11       2    R8,R9                     R        RL05                            
   12       2    R10,R12                   332R    2322 156 13321    RL05           
   13       1    R11                       1K82    2322 156 11822    RL05           
   14       1    R13                       1K    2322 156 11002    RL05             
   15       1    R14                       3K32    2322 156 13322    RL05           
   16       7    TP1,TP2,TP3,TP4,TP5,TP6,  TP    4022 007 45420    TP               
                 TP7
   17       1    U1                        LF353    9334 952 60682    8DIP300       
   18       1    U2                        LM337LZ    9336 497 30682    TO92        
   19       1    U3                        LM317LZ    9336 056 80682    TO92        

