/***************************************************************************/
/*	Copyright ProTeleVision Technologies A/S, BRONDBY 2000						*/
/*	Project:		PT5230 Digital Video Generator										*/
/*	Module:		SW5230.H																		*/
/*	Author:		Kim Engedahl, DEV															*/
/*	Org. date:	980208																		*/
/*	Rev. date:	000508, KEn, DEV															*/
/*	Status:		Version 1.7																	*/
/*																									*/
/*	Changes:																						*/
/* 000508: Released as 4008 002 07331													*/
/* 991026: Released as 4008 002 06819													*/
/* 990421: Released as 4008 002 06817													*/
/* 990304: Released as 4008 002 06816													*/
/* 981126: Released as 4008 002 06815													*/
/* 9809xx: Released as 4008 002 06814													*/
/* 980825: Released as 4008 002 06813													*/
/* 980616: Released as 4008 002 06812													*/
/* 980514: Released as 4008 002 06811													*/
/***************************************************************************/

#define PT5230SWVersion				28					// Software version
