
# Makefile for Cygnal 8051F320 flashUSB loader  project
# See link.rsp for linker args for 32 bits protected mode console
# application !


BCB = C:\BC5\BIN

DEBUG=0

CC = $(BCB)\bcc32
LN = $(BCB)\ilink32

!if$(DEBUG)
CFLAGS = -c -K -WC -v -P -VF
!else
CFLAGS = -c -K -WC -P -VF
!endif

.c.obj:
      $(CC) $(CFLAGS) $&.c

OBJECTS = flashUSB.obj

flashUSB.exe: $(OBJECTS)

  $(LN) @linkrsp

flashUSB.obj: flashUSB.c

