/* Size of Error Window: displayError(); */

#define	ErrLeft		165
#define	ErrTop		118
#define	ErrRight		475
#define	ErrBottom	232
#define	ErrWidth		( ErrRight - ErrLeft)


/* Size of About window: doAbout(); */

#define	AbLeft		120
#define	AbTop			112
#define	AbRight		520
#define	AbBottom		238
#define	AbWidth		( AbRight - AbLeft)

/* External variables used in MESSAGE.C: */

extern const char* ButtonText[];

