/***************************************************************************/
/*	Copyright PHILIPS TV TEST EQUIPMENT A/S, BRONDBY 1997							*/
/*	Project:		PT5210 VariTime digital sync generator, master					*/
/*	Module:		SW5210.H																		*/
/*	Author:		Kim Engedahl, DEV															*/
/*	Org. date:	970828																		*/
/*	Rev. date:	971028, KEn DEV															*/
/*	Status:		Version 1.0																	*/
/*																									*/
/*	Changes:																						*/
/* 970911 SWVersion changed to PT5210SWVersion										*/
/***************************************************************************/

#define PT5210SWVersion				25					// Software version
