/****************************************************************************/
/* MODULE:                                                                  */
/*   rtcl_nul.h - Controller & device independent null types                */
/****************************************************************************/
/*
 *   RTXCio    
 *   Copyright (c) 
 *   Embedded System Products, Inc.
 *   ALL RIGHTS RESERVED
*/
/****************************************************************************/
#ifndef _RTCL_NUL_H_  /* { _RTCL_NUL_H_ */
#define  _RTCL_NUL_H_

#ifdef __cplusplus /* { */
extern "C" {
#endif /* } __cplusplus */

#define NULLUHEADER ((PDU_HEADER *)0)  /* null physical unit header pointer */
#define NULLCNTLR ((CNTLR_UNIT *)0)         /* null controller unit pointer */

#ifdef __cplusplus /* { */
}
#endif /* } __cplusplus */

#endif    /* } _RTCL_NUL_H_ */

/* End of the RTCL_NUL.H module */
