
# Makefile for FPGAPC   project

COMP = c:\bc3


DEBUG=0

!if$(DEBUG)
CFLAGS = -c -K -WC -v
!else
CFLAGS = -c -K -WC
!endif


CC = $(COMP)\bin\bcc
LN = $(COMP)\bin\tlink

LIBS  = $(COMP)\LIB\CS.lib
START = $(COMP)\LIB\C0S.obj

.c.obj:
      $(CC) $(CFLAGS) $&.c

OBJECTS = FPGAPC.obj

test.exe: $(OBJECTS)
  $(LN) @linkresp.bc3

FPGAPC.obj:   FPGAPC.c
