/***************************************************************************/
/*	Copyright ProTeleVision Technologies A/S, BRONDBY 2000						*/
/*	Project:		PT5201 Compact VariTime Sync Generator								*/
/*	Module:		TEST.H																		*/
/*	Author:		Kim Engedahl, DEV															*/
/*	Org. date:	990819																		*/
/*	Rev. date:	000315, KEn, DEV															*/
/*	Status:		Version 1.0																	*/
/*																									*/
/*	This module contains no functions													*/
/*																									*/
/*	Changes:																						*/
/*																									*/
/***************************************************************************/
#ifndef _TEST_H
#define _TEST_H


#define maxHWTest	2

extern byte user_memory_test( void);
extern byte NVRAM_memory_test( void);

#endif
