/*
********************************************************************
* Project	: PT5210  Time Code Converter
* Filename	: TIME.H
* Version	: 1.1
* Purpose	: Definitions file
* Org.date	: 960717
* Author	: PRC
********************************************************************
HISTORY:
970xxx RELEASED 1.1
970120 Changed name from VARS.C
*/

typedef unsigned int UI;
typedef unsigned char UC;

#define XB	XBYTE

// CONSTANTS:
