/***************************************************************************/
/*	Copyright PHILIPS TV TEST EQUIPMENT A/S, BRONDBY 1997							*/
/*	Project:		PT5210 VariTime digital sync generator, master					*/
/*	Module:		SW5210.H																		*/
/*	Author:		Kim Engedahl, DEV															*/
/*	Org. date:	970828																		*/
/*	Rev. date:	991008, KEn DEV															*/
/*	Status:		Version 1.5																	*/
/*																									*/
/*	Changes:																						*/
/* 970911 SWVersion changed to PT5210SWVersion										*/
/* 020627 for 913 modification (moving text in SDI) ver is 35 JK           */
/***************************************************************************/

#define PT5210SWVersion	35  // Software version
