@ECHO OFF
REM Calling chanpict.exe with appropriate codes for displaying the PAL-G
REM indian head test pattern.
REM -----------------------------------------------------------------------
REM
REM Author:         Mikael Nadelmann
REM
REM First created:  08/01/93
REM
REM New update:     08/01/93  Adding call.
REM New update:     30/03/93  Editing call.
REM
REM -----------------------------------------------------------------------


chanpic3 NAS=702 NAL=486 XZ0=100 XZ1=182 XZ2=182 YZ0=0 YZ1=5 YZ2=5 XO0=0 YO0=1 Mode=2