// VARS.H


// BITS IN BYTE: DOFLAGS(@20)
extern bit	dolock;
extern bit	dosch;
extern bit	domode;
extern bit	doknap;
extern bit	doline7;
extern bit	nsf;

// BITS IN BYTE outsb (@21): 
extern bit	syncav;
extern bit	lockbit;
extern bit	spgint;
extern bit	buav;
extern bit	pal;
extern bit	slowlock;
extern bit	secam;
extern bit	tau;

// BITS IN BYTE savesb(@22): 
extern bit genlocken;
extern bit pplocken;

