# @(#)makefile	1.4
#------------------------------------------------------------------------------
# Makefile for building the 'testio' example program.
#
# Make sure the bin directory is in your PATH environment. Then type:
#
#	mkxa
#
# Please read the file readme.txt for more information
#------------------------------------------------------------------------------

ALL		: testio.abs

##
## definitions of configuration dependent options and controls
##

ifdef V
VERBOSE		= -v
endif

ifdef LARGE
SET_MODEL	= -Ml
else
SET_MODEL	= -Ms
endif

CCFLAGS		= $(VERBOSE) $(SET_MODEL) -g -Wc-w303
LDFLAGS		= $(VERBOSE) $(SET_MODEL) $(SET_LIB)

##
## the rules for building the example application
##

testio.abs	: testio.obj

testio.obj	: testio.c 

clean:
	$(exist testio.abs del testio.abs)
	$(exist testio.sym del testio.sym)
	$(exist testio.map del testio.map)
	$(exist testio.obj del testio.obj)
