# @(#)makefile	1.1 11/18/96
#------------------------------------------------------------------------------
# Makefile for building the FpSIGFPE example.
#
# Make sure the bin directory is in your PATH environment. Then type:
#
#	mkxa
#
# Please read the file readme.txt for more information
#------------------------------------------------------------------------------

ALL		: fpsigfpe.abs

##
## definitions of configuration dependent options and controls
##

ifdef 		V
VERBOSE		= -v
endif

ifdef 		LARGE
SET_MODEL	= -Ml
else
SET_MODEL	= -Ms
endif

CCFLAGS		= $(VERBOSE) $(SET_MODEL) -g -fptrap
LDFLAGS		= $(VERBOSE) $(SET_MODEL) -g -fptrap

##
## the rules for building the example application
##

fpsigfpe.abs	: fpsigfpe.obj

fpsigfpe.obj	: fpsigfpe.c

clean		:
		$(exist fpsigfpe.abs del fpsigfpe.abs)
		$(exist fpsigfpe.sym del fpsigfpe.sym)
		$(exist fpsigfpe.map del fpsigfpe.map)
		$(exist fpsigfpe.obj del fpsigfpe.obj)
