# @(#)makefile	1.3 12/24/96
#------------------------------------------------------------------------------
# Makefile for building the Fptrap example.
#
# Make sure the bin directory is in your PATH environment. Then type:
#
#	mkxa
#
# Please read the file readme.txt for more information
#------------------------------------------------------------------------------

ALL		: fptrap.abs

##
## definitions of configuration dependent options and controls
##

ifdef 		V
VERBOSE		= -v
endif

ifdef 		LARGE
SET_MODEL	= -Ml
else
SET_MODEL	= -Ms
endif

CCFLAGS		= $(VERBOSE) $(SET_MODEL) -g -fptrap
LDFLAGS		= $(VERBOSE) $(SET_MODEL) -g -fptrap

##
## the rules for building the example application
##

fptrap.abs	: fptrap.obj

fptrap.obj	: fptrap.c

clean		:
		$(exist fptrap.abs del fptrap.abs)
		$(exist fptrap.sym del fptrap.sym)
		$(exist fptrap.map del fptrap.map)
		$(exist fptrap.obj del fptrap.obj)
