/***************************************************************************/
/*	Copyright ProTeleVision Technologies A/S, BRONDBY 2000						*/
/*	Project:		PT5201 Compact VariTime Sync Generator								*/
/*	Module:		MAIN.H	 																	*/
/*	Author:		Kim Engedahl, DEV															*/
/*	Org. date:	990716																		*/
/*	Rev. date:	000307, KEn, DEV															*/
/*	Status:		Version 1.0																	*/
/*																									*/
/*	This module contains no functions													*/
/*																									*/
/*	Changes:																						*/
/*																									*/
/***************************************************************************/
#ifndef _MAIN_H
#define _MAIN_H

extern volatile _near byte UserTimer;

#endif