# @(#)makefile	1.5
#------------------------------------------------------------------------------
# Makefile for building the 'Whetstone' benchmark.
#
# Make sure the bin directory is in your PATH environment. Then type:
#
#	mkxa
#
# Please read the file readme.txt for more information
#------------------------------------------------------------------------------

ALL		: whet.abs

##
## definitions of configuration dependent options and controls
##

ifdef 		V
VERBOSE		= -v
endif

ifdef 		LARGE
SET_MODEL	= -Ml
else
SET_MODEL	= -Ms
endif

ifdef SIZE
OPTIM		= -O1
else
SET_POUT	= -DPOUT
OPTIM		= -O2 -DMEASURE_TIME
endif

ifdef 		SINGLE
SET_SINGLE	= -F
endif

CCFLAGS		= $(VERBOSE) $(SET_MODEL) $(OPTIM) $(SET_SINGLE) $(SET_POUT) -g -Wc-w91
LDFLAGS		= $(VERBOSE) $(SET_MODEL) $(SET_SINGLE)


##
## the rules for building the example application
##

whet.abs	: whet.obj

clean		:
		$(exist whet.abs del whet.abs)
		$(exist whet.sym del whet.sym)
		$(exist whet.map del whet.map)
		$(exist whet.obj del whet.obj)
