[COREGEN.VERILOG Component Instantiation.fifo]
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="fifo YourInstanceName ("
text007="    .din(din),"
text008="    .rd_clk(rd_clk),"
text009="    .rd_en(rd_en),"
text010="    .rst(rst),"
text011="    .wr_clk(wr_clk),"
text012="    .wr_en(wr_en),"
text013="    .dout(dout),"
text014="    .empty(empty),"
text015="    .full(full));"
text016=""
text017=" "
type=template
[COREGEN.VHDL Component Instantiation.fifo]
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component fifo"
text005="    port ("
text006="    din: IN std_logic_VECTOR(19 downto 0);"
text007="    rd_clk: IN std_logic;"
text008="    rd_en: IN std_logic;"
text009="    rst: IN std_logic;"
text010="    wr_clk: IN std_logic;"
text011="    wr_en: IN std_logic;"
text012="    dout: OUT std_logic_VECTOR(19 downto 0);"
text013="    empty: OUT std_logic;"
text014="    full: OUT std_logic);"
text015="end component;"
text016=""
text017=""
text018=""
text019=" "
text020="-------------------------------------------------------------"
text021=" "
text022="-- The following code must appear in the VHDL architecture body."
text023="-- Substitute your own instance name and net names."
text024=" "
text025="your_instance_name : fifo"
text026="        port map ("
text027="            din => din,"
text028="            rd_clk => rd_clk,"
text029="            rd_en => rd_en,"
text030="            rst => rst,"
text031="            wr_clk => wr_clk,"
text032="            wr_en => wr_en,"
text033="            dout => dout,"
text034="            empty => empty,"
text035="            full => full);"
text036=" "
type=template
