# @(#)makefile	1.5 9/4/97
#------------------------------------------------------------------------------
# Makefile for building the 'Dhrystone' benchmark version 1.1 and 2.1.
#
# Make sure the bin directory is in your PATH environment. Then type:
#
#	mkxa
#
# Please read the file readme.txt for more information
#------------------------------------------------------------------------------

ALL		: dhry_1.abs

##
## definitions of configuration dependent options and controls
##

ifdef 		V
VERBOSE		= -v
endif

ifdef		LARGE
SET_MODEL	= -Ml 
else
SET_MODEL	= -Ms
endif

ifdef		SIZE
OFLAGS		= -O1 -F
else
OFLAGS		= -O2
endif

CCFLAGS		= $(VERBOSE) $(SET_MODEL) $(OFLAGS) -g -DCTimer -Wc-w91 -Wc-w66 -Wc-w303
LDFLAGS		= $(VERBOSE) $(SET_MODEL) -Wlk-w1

##
## the rules for building the applications
##

dhry_1.abs	: dhry_1.obj dhry_2.obj timers_b.obj

dhry_1.obj	: dhry_1.c

dhry_2.obj	: dhry_2.c

timers_b.obj	: timers_b.c


clean		:
		$(exist dhry_1.abs del dhry_1.abs)
		$(exist dhry_1.sym del dhry_1.sym)
		$(exist dhry_1.map del dhry_1.map)
		$(exist dhry_1.obj del dhry_1.obj)
		$(exist dhry_2.obj del dhry_2.obj)
		$(exist timers_b.obj del timers_b.obj)
