//-----------------------------------------------------------------------------
// netfinder.h
//-----------------------------------------------------------------------------
// Copyright 2006 Silicon Laboratories, Inc.
//
// Description:
// 	This file contains user defined constants used by the TCP/IP Stack.
//
// Generated by TCP/IP Library Builder Version 3.23

//-----------------------------------------------------------------------------
// User Configurable Settings
//-----------------------------------------------------------------------------

#define NETFINDER_PORT        3040              // Defines the UDP port assigned
                                                // to the Netfinder protocol

extern bit ethernet_reconfigure;				// Being used to restart the MCU after IP change.
extern bit netfinder_need_reset_socket;
extern bit b_reset_password;

extern unsigned char netfinder_reset_socket_delay;
extern unsigned char netfinder_buff[];
// Customization Strings:
// These strings will be displayed on the front panel of the Netfinder 
// application. Add quotes ("") around the string, but do not add a semicolon
// at the end of the line. STRING_A and STRING_B describe the embedded system.
// STRING_C and STRING_D describe the first and second events.
#define STRING_A "PT5300"
#define STRING_B "HD-SD Varitime Sync Generator"
#define STRING_C "Uptime"
#define STRING_D "UTC"

//-----------------------------------------------------------------------------
// Function Prototypes
//-----------------------------------------------------------------------------
extern int netfinder_start(void);             
extern int netfinder_process_packet(void);
//extern void netfinder_update_RTC(void);
//extern void netfinder_reset_event1(void);
//extern void netfinder_reset_event2(void);
extern void ETHFlashReset(void);				// Write default settings to CP2200.
//extern void erase_network_settings(void);		// Used for debug.
//-----------------------------------------------------------------------------
// Global Variables
//-----------------------------------------------------------------------------
extern int netfinder_socketno;
extern void write_network_settings(void);
extern unsigned char DHCP_Enable;
extern unsigned char TELNET_Enable;
