
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 8.1 EDK_I.18.7
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xopbarb.h"

/*
* The configuration table for devices
*/

XOpbArb_Config XOpbArb_ConfigTable[] =
{
	{
		XPAR_MB_OPB_DEVICE_ID,
		XPAR_MB_OPB_BASEADDR,
		XPAR_MB_OPB_OPB_NUM_MASTERS
	}
};


