# @(#)makefile	1.5 9/19/97
#------------------------------------------------------------------------------
# Makefile for building the 'c' example program.
#
# Make sure the bin directory is in your PATH environment. Then type:
#
#	mkxa
#
# Please read the file readme.txt for more information
#------------------------------------------------------------------------------

ALL		: builtin.src intrpt.src

##
## definitions of configuration dependent options and controls
##

ifdef V
VERBOSE		= -v
endif

ifdef LARGE
SET_MODEL	= -Ml
else
SET_MODEL	= -Ms
endif


##
## the rules for building the example application
##

builtin.src	: builtin.c
	ccxa -cs $(VERBOSE) $(SET_MODEL) -gn -s  -Cxag3 builtin.c

intrpt.src	: intrpt.c
	ccxa -cs $(VERBOSE) $(SET_MODEL) -gn -s intrpt.c

 
clean		:
	$(exist builtin.src del builtin.src)
	$(exist intrpt.src del intrpt.src)
