
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 8.1 EDK_I.18.7
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xuartlite.h"

/*
* The configuration table for devices
*/

XUartLite_Config XUartLite_ConfigTable[] =
{
	{
		XPAR_DEBUG_MODULE_DEVICE_ID,
		XPAR_DEBUG_MODULE_BASEADDR,
		XPAR_DEBUG_MODULE_BAUDRATE,
		XPAR_DEBUG_MODULE_USE_PARITY,
		XPAR_DEBUG_MODULE_ODD_PARITY,
		XPAR_DEBUG_MODULE_DATA_BITS
	},
	{
		XPAR_RS232_DEVICE_ID,
		XPAR_RS232_BASEADDR,
		XPAR_RS232_BAUDRATE,
		XPAR_RS232_USE_PARITY,
		XPAR_RS232_ODD_PARITY,
		XPAR_RS232_DATA_BITS
	}
};


