# @(#)makefile	1.13
#------------------------------------------------------------------------------
# Makefile for building the 'demo.abs' application.
# To build the example, type:
#
#	mkxa
#
# Please read the file readme.txt for more information
#------------------------------------------------------------------------------

all		: demo.abs

ifdef V
VERBOSE         = -v
endif

SET_MODEL       = -Ms
SET_LIB         = -nolib -lcs

CCFLAGS         = $(VERBOSE) $(SET_MODEL) -g
LDFLAGS         = $(VERBOSE) $(SET_MODEL) $(SET_LIB)

##
## the rules for building the example application
##

demo.abs	: demo.obj addone.obj

demo.obj	: demo.c
	$(CC) $(CCFLAGS) -c -Wc-w303 demo.c

addone.obj      : addone.src
        $(CC) $(CCFLAGS) -c addone.src

clean		:
	$(exist demo.obj $(RM) demo.obj)
	$(exist addone.obj $(RM) addone.obj)
	$(exist demo.map $(RM) demo.map)
	$(exist demo.abs $(RM) demo.abs)
